### ISSUE TITLE
Remove "path" from labels to keep cardinality low

### ISSUE THREAD

**Issue by emmenko** [tdeekens/promster#1]

**Comment by tdeekens** [comment]
Thanks for the issue. Raising cardinality problems is also good 😁. 

I‘ve added some tests to ensure that the default normalizer does at least something:

1. Should we add more specs?
2. What do you see missing?

Reference to the spec: https://github.com/tdeekens/promster/blob/master/packages/metrics/modules/normalizers/path/path.spec.js

**Comment by tdeekens** [comment]
As a side note: you can always pass a custom normalizer during configuration to be more strict. However, let me know if we definitely don’t normalize enough.

**Comment by emmenko** [comment]
I got a bit lost but ok, as long as you are aware of the cardinality problem and that the library handles this I'm fine 😇

**Comment by tdeekens** [comment]
It tries to offer a reasonably sane default. It's mostly aligned with the 3-4 other exporters which do the same. Given that more have this we can either drop the url or try to be even more strict. I've looked into how and can't really think of a way for now. 

Thanks again for raising it!
