### ISSUE TITLE
Up gauge

### ISSUE THREAD

**Issue by jmfsilva** [tdeekens/promster#113]
The up metric is created, but it is never set nor exposed to be set?

Am i missing something?

**Comment by tdeekens** [comment]
It should be exposed. I just checked on a service I use at work it has the 

```txt
# HELP up 1 = up, 0 = not up
# TYPE up gauge
up 0
```

but while pasing I notice that it should be `1` 😕. Is that what you mean?

**Comment by jmfsilva** [comment]
Yes. It is always 0.

**Comment by jmfsilva** [comment]
By exposed i mean, i cannot set it to anything. At it is always 0

**Comment by tdeekens** [comment]
Thanks. Yeah that definately sounds wrong. I never noticed cause I use other health endpoints and not that Promehteus Gauge. I will try to look into it soon. Thanks. While writing: how and where would you rely on it and would you already think of a preferred way of setting it?

**Comment by jmfsilva** [comment]
I guess the best way would be to register to an app event. But, from express documentation, the application that is received on the createMiddleware has only one event (onmount http://expressjs.com/en/4x/api.html#app.onmount). 

Maybe expose a function that can set this metric?
More or less like the getRequestRecorder.

**Comment by tdeekens** [comment]
> More or less like the getRequestRecorder.

Yeah that's what I thought of too. I think hooking into either express of hapi internals doesn't really work too well as they differ and we'd tie the library to breaking changes on that end.

**Comment by jmfsilva** [comment]
I'm using the current workarround:

```
import { register } from 'prom-client';

app.listen(process.env.PORT || 3000, error => {
  if (error) {
    console.error(error);
  } else {
    register.getSingleMetric("up").set(1);
  }
  console.log('🚀 started');
});

```

**Comment by tdeekens** [comment]
Let me know what you think: https://github.com/tdeekens/promster/pull/114

**Comment by jmfsilva** [comment]
Done :+1:

**Comment by tdeekens** [comment]
https://github.com/tdeekens/promster/releases/tag/%40promster%2Fexpress%402.2.0
