### ISSUE TITLE
Implement http_server_requests_total metric

### ISSUE THREAD

**Issue by santiagopoli** [tdeekens/promster#13]
While the current metrics can be used for almost any use case, it would be nice to provide this metric to be more consistent with other prometheus exporters. 

Prometheus official docs also use this metric as an example:

https://prometheus.io/docs/prometheus/latest/querying/examples/
https://github.com/prometheus/docs/blob/master/content/docs/practices/naming.md#metric-names

While the official docs use http_requests_total, a lot of libraries are using http_server_requests_total as an alternative because it's more declarative. Either way, this can be solved with relabeling configs.

Some insights about this can be found on https://www.robustperception.io/on-the-naming-of-things

A lot of projects leverage on Grafana Dashboards which display graphs and values based on this metric. For example, we have a dashboard which provides metrics for all of our services. Having to add a second query only to provide compatibility with our NodeJS services seems very odd.

As satated by @tdeekens in https://github.com/tdeekens/promster/pull/12, the requests/s example provided in the prometheus docs can be achieved by doing

`sum(rate(http_request_duration_buckets_milliseconds_count[1m])) * 60)`

Do you think it would be relevant to add this metric? We can provide an option to disable it as well.

Cheers!

**Comment by tdeekens** [comment]
Thanks for the issue. I do not really mind adding it. Especially as it can be disabled by default and behind a config flag. I just wanted to clarify, as I felt that was missing on previous dicussions, that queries achieving the intended result can actually be performed on the current metrics. I understand the argument to have one, consistent to other exporters, total metric to reuse it in dashboards. Just for completeness, not to drive a point home, Grafana also supports multiple graphs/queries in a chart and with recording rules you could hide details quite nicely. 

That said, as there is still a valid use case from a charting and consistency perspective

1. I‘d vote for http_requests_total
2. I‘d vote for disabling it by default

Would that all be fine by you?

**Comment by santiagopoli** [comment]
Looks fine. Do you want me to implement it or you prefer doing it?

**Comment by tdeekens** [comment]
I am wondering to actually enable it by default. Maybe it makes the library more approachable coming from examples. What do you think?

I was planning on moving to seconds by default and only the summary and counter by default. Percentiles can be computed on the client which is often slow. However you can then use recording rules. Maybe that can all go into v2. 

Feel free to give it a start if you want to. I am happy to take over as soon as I can.
