### ISSUE TITLE
Promster hapi plugin not working with hapi V-13

### ISSUE THREAD

**Issue by kamal-bhatt** [tdeekens/promster#131]
**Describe the bug**

**To Reproduce**

1. Given '...'
2. Then '....'
3. That '....'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22490116/57216372-54bbf280-700d-11e9-880f-5c7b6c480dc7.png)

**Additional context**
![image](https://user-images.githubusercontent.com/22490116/57216400-630a0e80-700d-11e9-9169-f405a44519f5.png)

**Comment by tdeekens** [comment]
Thanks for reporting. Would you mind investigating and maybe even creating a PR?

**Comment by jasonyihk** [comment]
another thing which I need to point out is that for hapijs < 17.0, `server.events.on('response',` will cause issue and need to upgrade hapijs to 17.+
a work around is to use `server.ext('onPreResponse',` instead in plugin.js

**Comment by tdeekens** [comment]
Could we do some "version sniffing" to make it work in both cases? Either by reading the Hapi version or by checking if `server.events.on` exists?

**Comment by jasonyihk** [comment]
suggestion to change to `server.ext('onPreResponse',` since it is available in 16.x, 17.x & 18.x . hopefully, it will not be deprecated soon.

**Comment by tdeekens** [comment]
Ok.

**Comment by tdeekens** [comment]
I added sniffing of the version to #147.

**Comment by tdeekens** [comment]
Please check `@promster/hapi@2.2.3`. It could contain the fixes needed for this.
