### ISSUE TITLE
Default registry does not work with prom-client AggregatorRegistry

### ISSUE THREAD

**Issue by Bondza** [tdeekens/promster#167]
**Describe the bug**
Using prom-client `AggregatorRegistry.setRegistries` with promster `defaultRegister` throws an error.

```
TypeError: Expected Registry, got object
    at node_modules/prom-client/lib/cluster.js:140:11
    at Array.forEach (<anonymous>)
    at Function.setRegistries (node_modules/prom-client/lib/cluster.js:138:8)
    at Object.<anonymous> (test.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

**To Reproduce**
1. Install prom-client and @promster/express
```sh
npm install prom-client @promster/express
```
2. Run
```js
const { AggregatorRegistry } = require('prom-client');
const { defaultRegister } = require('@promster/express');

AggregatorRegistry.setRegistries(defaultRegister);
```

**Expected behavior**
`defaultRegister` can be used with `AggregatorRegistry`.

**Comment by tdeekens** [comment]
Thanks for the issue. I will look into it and fix the issue as your described in "2. Run" within promster.

**Comment by Bondza** [comment]
Great! Forgot to say I'm using node version `12.4.0`.
Also, is it possible to use a Registry other than `defaultResgiter` with promster? I tried creating a prom-client `Registry` and then use that with promster but I couldn't figure out how to use the register with `createMiddleware`.

**Comment by tdeekens** [comment]
> Also, is it possible to use a Registry other than defaultResgiter with promster? I tried creating a prom-client Registry and then use that with promster but I couldn't figure out how to use the register with createMiddleware.

Not yet. Nobody had a usecase for it yet. I can also look into it in another PR. Can you elaborate what the benefit of it is and maybe propose an API you would like? Thanks!

**Comment by Bondza** [comment]
I don't really have a use case either, it was just an attempt at getting around this issue.

But I did get this to work, I used `promster.Prometheus` instead of using `prom-client` directly. Like this:
```js
const { defaultRegister, Prometheus } = require('@promster/express');
const { AggregatorRegistry } = Prometheus;
AggregatorRegistry.setRegistries(defaultRegister);
```
I'm not sure it is possible to make my previous example work. Because of how the modules are loaded.
```
require('prom-client') > node_modules/prom-client/index.js
require('@promster/express').Prometheus > node_modules/@promster/metrics/node_modules/prom-client/index.js
```
I guess that means that `require('@promster/express').defaultRegister` can never be an instance of `require('prom-client').Registry`?

**Comment by tdeekens** [comment]
I've looked into this a bit. 

> Also, is it possible to use a Registry other than defaultResgiter with promster?

To my understanding you can always use `const otherRegister = new Prometheus.Registry()` with promster and then use it:

```
const counter = new Prometheus.Counter({
  name: 'metric_name',
  help: 'metric_help',
  registers: [otherRegister]
});
```

This does not hold for the default metrics. Which however you can also reconfigure using `Prometheus.collectDefaultMetrics({timeout: 5000, register: otherRegister })`.

That leaves us with the `AggregatorRegistry` where I think you approach is correct of doing: `Prometheus.AggregatorRegistry.setRegistries(defaultRegister)`.

> I guess that means that require('@promster/express').defaultRegister can never be an instance of require('prom-client').Registry?

I think so not. This is more `prom-client` internal to my understanding where the default register is just implicitely created in `prom-client`.

In all, I am unsure if we should expose more APIs from promster instead of just `prom-client` by wrapping it. That's just more API surface and might confuse people. What's you take on this?

**Comment by r4j4h** [comment]
Would the metrics package treating prom-client as a peerDependency help the situation? End users would have to install prom-client themselves to use this project, but then they may be able to share prom-client Registry instances.

**Comment by tdeekens** [comment]
That's a good idea. I don't remember putting much thought into not doing that initially. Would be a breaking change but easy to migrate from.

**Comment by tdeekens** [comment]
What do you all think: https://github.com/tdeekens/promster/pull/178? :)
