### ISSUE TITLE
fastify support

### ISSUE THREAD

**Issue by dimonnwc3** [tdeekens/promster#168]
**Is your feature request related to a problem? Please describe.**
Would be nice to use this module with https://github.com/fastify/fastify

**Describe the solution you'd like**
Adding middleware for fastify

what do you think?

**Comment by tdeekens** [comment]
Sounds great. Do you have any experience with fastify? Does it have a middleware/plugin construct we could use to hook into any request?

**Comment by dimonnwc3** [comment]
yep, they have plugin system and I can submit initial PR

**Comment by tdeekens** [comment]
> yep, they have plugin system and I can submit initial PR

That'd be super cool. Especially the integration part I would have to study. I can help bringing it across the finish line in terms of: docs, testing and releasing obviously.

Thanks a lot!

**Comment by dimonnwc3** [comment]
thanks for fast response and release 👍
