### ISSUE TITLE
pass req to normalizePath() to allow for more flexibility

### ISSUE THREAD

**Issue by pepmartinez** [tdeekens/promster#201]
I was wondering whether passing the full req object to the normalizePath (as second argument) would be a nice addition to ease path normalization; for example, if using express one could use the [req.route](https://expressjs.com/en/4x/api.html#req.route) info to map paths like /a/666/store/22334455 into '/a/:areaId/id/:storeId', thus reducing cardinality a lot

**Comment by tdeekens** [comment]
This sounds nice. I see to options considering all packages

1. Make the `request` and in other cases `response` a second argument to any normalizer
   - This would be a non-breaking change
2. Change the API of our default normalizers any by that others may be setting up to always only receive `request` and/or `response`
   - This is a breaking change to the library but allows others to be more flexible

Do you have a preference towards any of those options?

**Comment by tdeekens** [comment]
I will keep the signature kind of like `normalizer(suggestion: mixed, { request, response })`. This is non-breaking, works for all packages and gives better flexibility while keeping the suggested value in the 1st position.

**Comment by pepmartinez** [comment]
perfect, that's pretty much what I had in mind, thanks a lot

**Comment by andrastothtw** [comment]
@pepmartinez or @tdeekens Can you give an example how does this solve the case of reducing the cardinality when you have URL like: `:id/:name-of-a-thing` which is parsed to `#val/some-name-for-some-thing`? It is creating us a lot of unnecessary metrics since the name of the thing varies by language.

**Comment by pepmartinez** [comment]
the modification allows you to see the original request on a custom normalizePath. Thus, you can use the route path (which is the 'templated' path) if available. Something like this:
```

app.use (promster.createMiddleware({
    app: app,
    options: {
      normalizePath: (full_path, {req, res}) => (req.route ? path.join (req.baseUrl, req.route.path) : full_path.split ('?')[0])
    }
  }));
```
