### ISSUE TITLE
metricPrefix is not applied on the http_requests_total metric

### ISSUE THREAD

**Issue by morriskimani** [tdeekens/promster#257]
**Describe the bug**
It seems that **metricPrefix** option is not applied consistently on all collected metrics. Specifically, the prefix is not applied on the **http_requests_total** metric.

**To Reproduce**

1. Given 'You have created middleware with metricPrefix set to my_nice_prefix_'
2. Then 'Start the app and make a GET request to the /metrics endpoint'

**Expected behavior**
I would expect all metrics to be prefixed with the provided prefix i.e. **my_nice_prefix_**. This happens for all metrics apart from the **http_requests_total** metric. See annotated screenshot below:

**Screenshots**
<img width="946" alt="Screenshot 2019-11-04 at 17 22 50" src="https://user-images.githubusercontent.com/20963766/68133366-e5c24680-ff28-11e9-9ff6-fe5f20e7c166.png">
**Additional context**
I am using _@promster/express_

**Comment by tdeekens** [comment]
Thanks for reporting. Will look into it.

**Comment by morriskimani** [comment]
@tdeekens I'm actually looking into submitting a fix 🙂

**Comment by tdeekens** [comment]
Nice. Thanks. I found the issue too. You go ahead. Thanks for the contribution!

**Comment by mortenko** [comment]
Hi @tdeekens @morriskimani  I dont want to open new issue so I will ask here.   Do you know how to apply metricsPrefix option on custom metrics ? Or it's there different way how to do it ?

**Comment by tdeekens** [comment]
Good question. The answer is: you will have to do that yourself. We/I actually also have to do that. If we wanted that automated we would have to wrap the whole Promtheus API so that e.g. `new Prometheus.Counter` is `promster.createCounter` so that we can apply the prefix. I didn't want to do that for now as the cost benefit didn't weigh to clearly. As you can just apply the constant of the prefix yourself. Makes sense?

**Comment by mortenko** [comment]
I understand but in my case it could be quite helpful.  I have microservice arch. Every my service could have different (or they can share) custom metrics. Now, I decided to create npm module that will be let's say wrapper of your module with some additional proficiency.  Then I can pass option with metricsPrefix, which apply across whole metrics in given service. So I can easily re-use it in every service.

**Comment by tdeekens** [comment]
Hm, yeah what your library/npm module would do is just:

```js
const createPromtheusMetrics = (Prometheus, options) => metricOfType => {
   switch (metricOfType) {
     case: 'couter': {
        return new Promtheus.Counter({name: `${options.metricsPrefix}...`})
     }
     // ...
   }
}
```

sort of what we would have to do here too. You can maybe try building a little wrapper and then if you came to a good API open a PR here?
