### ISSUE TITLE
average response time last minute 

### ISSUE THREAD

**Issue by bananaspliff** [tdeekens/promster#294]
like micrometer with spring boot,
It will be a great feature to get how long the longest request took in the last minute 

ex:
http_server_requests_seconds_max{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/blah",} 0.040648985
http_server_requests_seconds_max{exception="ResourceNotFoundException",method="GET",outcome="CLIENT_ERROR",status="404",uri="/blahblah",} 0.0

**Comment by tdeekens** [comment]
Thanks. Yes that sounds interesting. What type of metric would you use for this?

**Comment by bananaspliff** [comment]
gauge : max response time by method
graph : average time (mean / max)

**Comment by tdeekens** [comment]
I am not able to implement this at this time. I am happy to review and integrate a PR. Until then I will close this.
