### ISSUE TITLE
MaxListenersExceededWarning during test runs

### ISSUE THREAD

**Issue by lerouxb** [tdeekens/promster#320]
I'm trying to use promster in a large hapi server with a lot of tests. The tests keep making and destroying lots of hapi server instances. For some subset of it, the promster plugin gets loaded. After a few tests, we get 

```
(node:55880) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 stats listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:281:17)
    at EventEmitter.addListener (events.js:297:10)
    at /redacted/node_modules/@promster/metrics/modules/create-gc-observer/create-gc-observer.js:20:8
```

My guess is that this is because of https://github.com/tdeekens/promster/blob/bec0ebfc93d2d1a09f2d86e70ffed5e407d81bc4/packages/metrics/modules/create-gc-observer/create-gc-observer.js#L20

It adds an event listener, but nothing ever cleans that up again.

This is probably only a problem during testing because normally in production code you're only going to make one hapi server and register promster once.

**Comment by tdeekens** [comment]
Thanks for the issue.

I created a `detectKubernetes` prop last week. It for now doesn't start the server when things do not run in k8s. I think something similar couldn be used to silence any metric setup under test.

**Comment by lerouxb** [comment]
My workaround is to put this in afterEach:

```
        const gc = GcStats();
        const listeners = gc.listeners('stats');

        for (const listener of listeners) {
            gc.off('stats', listener);
        }
```

**Comment by tdeekens** [comment]
Yeah that should work too. In the other case we could just pass something like `detectKubernetes: process.env.NODE_ENV === 'test'` which then skip any setup of those listeners in the first place. I am not super happy with the name detectKubernetes but it's what other libraries started using too (e.g. lightship).
