### ISSUE TITLE
TPromsterOptions not allowing for default options

### ISSUE THREAD

**Issue by roikoren755** [tdeekens/promster#378]
**Describe the bug**
I'm trying to create a middleware for an express app, using `@promster/express`' `createMiddleware` function. Before the package moved to TS, the following worked

```
createMiddleware({ options: { metricTypes: ['countOfGcs', 'durationOfGc', 'reclaimedInGc'] } });
```

and gave me the metrics I wanted. Now, however, after the move, I get an error from TS stating that `buckets` and `percentiles` are missing.

**To Reproduce**

Using TS 3.9, the following shows the error

```
import { createMiddleware } from '@promster/express';

createMiddleware({ options: { metricTypes: ['countOfGcs', 'durationOfGc', 'reclaimedInGc'] } });
```

**Expected behavior**
No TypeScript errors should occur

**Additional context**
Any place I found in the source code that uses either of these values has a fallback default value, so shouldn't these two be optional?

Right now, `TPromsterOptions` is defined with 

```
    buckets: [number];
    percentiles: [number];
}
```

From what I saw, these can be optional in the interface. I can open a PR with this small change, if that would be deemed appropriate, and would help

**Comment by tdeekens** [comment]
Thanks for opening such a eloborate issue!

I think what you're suggesting sounds right. Can you open a PR to fix it then we can take the discussion there.

**Comment by roikoren755** [comment]
Opened a PR at #379
