### ISSUE TITLE
Provide default Grafana dashboard

### ISSUE THREAD

**Issue by PMudra** [tdeekens/promster#38]
**Is your feature request related to a problem? Please describe.**

> PromQL is powerful and a great tool but can have a steep learning curve.

I totally agree with this statement in the readme as I am very new to Prometheus and Grafana.
For me it was easy to include promster into a hapi server app.
But building a Grafana dashboard is a little more complicated than I thought.

**Describe the solution you'd like**

I would appreciate an example Grafana dashboard definition as a starting point.

**Describe alternatives you've considered**

Well, building one on my own obviously :smile: 

**Additional context**

n/a

**Comment by tdeekens** [comment]
Interesting. A Grafana dashboard and the queries however highly depend on what environment you run in. When you run in Kubernetes your queries often contain pod names etc. I tried the example queries to help with that. Would you additionally want to have a JSON for Grafana you can just download?

**Comment by PMudra** [comment]
> Would you additionally want to have a JSON for Grafana you can just download?

Yes, if possible. I understand that providing a dashboard for production is impossible. I was thinking of a simple hello world dashboard that can be used by beginners like me. Including a JSON in this project would be the best way to do this, I think.

Most likely, the dashboard will be based on the queries provided in the readme. Maybe the `job` label should be used instead of `kubernetes_pod_name` as it is independent of the environment (?).

Do you have a dashboard like that already? I will for sure give it a try myself. But I don't think I can come up with a PR with a good solution very soon.

**Comment by tdeekens** [comment]
We do not have "simple hell world" dashboards but rather dashboards focussed on certain areas. Like one for memory consumption across all pods (Node.js services) and one for GC stats. Another for CPU usage (k8s throttling etc). I don't feel like I can extract a generic dashboard from that to be honest.

**Comment by PMudra** [comment]
Allright, I will have a look. Let's close this one for now :+1:
