### ISSUE TITLE
Build error without `allowSyntheticDefaultImports: true`

### ISSUE THREAD

**Issue by zone117x** [tdeekens/promster#459]
**Describe the bug**
This lib causes typescript project builds to fail unless enabling the `allowSyntheticDefaultImports` flag.

The build error:
```
node_modules/@promster/server/dist/modules/server/server.d.ts:1:8 - error TS1192: Module '"http"' has no default export.

1 import http from 'http';
```

**To Reproduce**
1. Create a typescript project with a `tsconfig.json` file that __*does not*__ have either of these options enabled:

```json
{
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
}
```

2. Import the promster/server lib:
```ts
import { createServer } from '@promster/server';
```

3. Run typescript build. See error.

**Expected behavior**
Properly typed libraries should not require the `allowSyntheticDefaultImports` or `esModuleInterop` flags to be enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/1447546/93459370-e6b25b80-f8e1-11ea-9c77-1cd5b1a6608b.png)

**Comment by tdeekens** [comment]
Thanks, I totally missed this issue in the mix of work and open source. What do you think could solve it? Changing the import of the `http` package?

**Comment by tdeekens** [comment]
Would you expect this to fix it? https://github.com/tdeekens/promster/pull/475

**Comment by zone117x** [comment]
Yes I believe so, thank you.

**Comment by tdeekens** [comment]
Is being released right now.
