### ISSUE TITLE
Typescript error with createMidleware function

### ISSUE THREAD

**Issue by natoehv** [tdeekens/promster#499]
Hi everybody!

I started to work with the new typescript integration (I'm using Express), and I got an error with the createMidleware function 
![image](https://user-images.githubusercontent.com/6584680/96865186-fc1a2880-143f-11eb-9f76-60a3c2790c68.png)
theapp variable is defined as `Express.Application`, 

TS Error:
`Type 'Application' is missing the following properties from type 'TApp': setTimeout, maxHeadersCount, timeout, headersTimeout, and 9 more.ts(2740)`

Should I change the typing of the application?

thanks you!

**Comment by tdeekens** [comment]
Thanks for opening.

`TApp` just extends `Server` from `http`. What are you passing in? Otherwise you could also get away with casting it. https://github.com/tdeekens/promster/blob/main/packages/express/modules/middleware/middleware.ts#L16

**Comment by natoehv** [comment]
I'm using an express application: 
```
const applyMiddleware = ({ app, path, regexPath, rewritePath }: PrometheusConfig) => {
  app.use(createMiddleware({
    app,
    options: {
      normalizePath: (originalpath) => {
        if (regexPath && !!regexPath.exec(originalpath)) {
          return rewritePath || 'customPath';
        }
        return originalpath;
      },
    },
  }));
```
```
export declare interface PrometheusConfig {
  app: express.Application;
  path: string;
  regexPath?: RegExp;
  rewritePath?: string;
}
```
and I use it:
```
const app = express();
const appProm = applyMiddleware({ app, path: promPath });
```

PD: I can't cast to TApp, because it doesn't export :(

**Comment by tdeekens** [comment]
Would it help you if we'd export it? Maybe try it with a fork. If it works I'd be happy to see a PR.

**Comment by natoehv** [comment]
exporting the class did not work, but if a change in the type of TApp, what do you think?

https://github.com/tdeekens/promster/pull/500

**Comment by tdeekens** [comment]
Awesome. Thanks for contributing.

**Comment by tdeekens** [comment]
Will be published from CI.

**Comment by natoehv** [comment]
thank you @tdeekens 👍 now is working fine 🥇
