### ISSUE TITLE
Minimist dependency fails package audit

### ISSUE THREAD

**Issue by dgg** [tdeekens/promster#528]
**Describe the bug**
After installation of package, audit checks in our pipelines fail.
The culprit are several **minimist** dependencies from _gc-stats_

**To Reproduce**

1. Install _@promster/fastify@4.0.0_
2. Run _npm audit --registry=https://registry.npmjs.org_ 

**Expected behavior**
No error. `found 0 vulnerabilities`

**Screenshots**
![Screenshot 2020-11-17 at 07 38 13](https://user-images.githubusercontent.com/1008304/99355086-f3363e80-28a7-11eb-8e2c-7eebd54f87c6.png)

**More information**
Reproduced in MacOS.
❯ node --version
v14.8.0
❯ npm --version
6.14.7
Also reproduces in Azure pipelines agent, Ubuntu 18.04

**Comment by tdeekens** [comment]
Thanks for reporting. Any suggestions on what we can do here specifically? Upon first sight it looks more like it needs fixing upstream?

**Comment by dgg** [comment]
It may very well need to be fixed upstream. In my particular case, I am ok without the GC stats so maybe extracting those metrics into their own package. But that may be more of an annoyance than anything 
But I get it, third (or nth) party audit problems are troublesome for everyone I just happened to "get it" from your dependency

**Comment by tdeekens** [comment]
Yes, if I could I'd move away from a library not passing an audit but if it's a transitive dependency or a core dependency to the library I don't see how that's possible. Can you also open an issue upstream maybe?

**Comment by dgg** [comment]
Yeah, I see the problem. I will try to identify where shall I open the issue. And let you know.

**Comment by dgg** [comment]
So far:
Installing _node-pre-gyp@0.16.0_ -> no audit problems

I cannot install gc-stats because it cannot be built and there is no prebuilt binary. -> no audit problems

When I install @prompster/metrics@4.1.13 -> the audit problems show off.

So, I am not really sure which upstream to create the issue in. no-pre-gyp has no issue and I cannot verify gc-stats because it does not build. Any hints?

**Comment by dgg** [comment]
I also tried to install @promster/metrics with the _--no-optional_ flag with no success, gc-stats still shows up in the package-lock and causes the audit problem

**Comment by tdeekens** [comment]
`gc-stats` is an optional dependency to the metrics packages which in turn is used by all integrations. To me it looks like `gc-stats` usines `mkdirp` which uses `minimist` which has the issue. We could add a hard resolution to minimist here if it is fixed there. Do we know if it is?

**Comment by dgg** [comment]
I am still looking for a solution, but some bigger fires need to be put down first 😉

**Comment by dgg** [comment]
We finally decided to implement ourselves the metrics we need from fastify in a very non-generic manner.
Thanks for your help and your approach to metrics
