### ISSUE TITLE
Content length histograms for requests and responses

### ISSUE THREAD

**Issue by raviqqe** [tdeekens/promster#702]
**Is your feature request related to a problem? Please describe.**

- Currently, we do not have a default way to track request and response body sizes of HTTP requests.

**Describe the solution you'd like**

- Metrics for histograms of the content-length header for requests and responses.

**Describe alternatives you've considered**

- Custom metrics by using `prom-client` or equivalent directly

**Additional context**

We want this feature as part of our monitoring system. While we've implemented this manually, that would be great if `promster` supports this out of the box.  Are there any needs by others?

BTW, thank you for this great tool!

**Comment by tdeekens** [comment]
That's a nice idea! I guess we'd have a custom histogram as suggested to then measure the response size in each plugin. What would be your preferred name for the metric? Would you be open to contributing this feature yourself?
