### ISSUE TITLE
`@promster/hapi` in version `6.1.0` causes an unhandled promise rejection

### ISSUE THREAD

**Issue by selaux** [tdeekens/promster#721]
**Describe the bug**

`@promster/hapi` in version `6.1.0` causes an unhandled promise rejection when using raw response object to build response in hapi:

```
TypeError: Cannot read properties of undefined (reading 'content-length')
    at Object.onResponseHandler [as listener] (/home/stefan/tmp/promster-issue/node_modules/@promster/hapi/dist/promster-hapi.cjs.dev.js:162:33)
    at module.exports.internals.Podium.emit (/home/stefan/tmp/promster-issue/node_modules/@hapi/podium/lib/index.js:221:110)
    at Request._finalize (/home/stefan/tmp/promster-issue/node_modules/@hapi/hapi/lib/request.js:514:27)
    at Request._abort (/home/stefan/tmp/promster-issue/node_modules/@hapi/hapi/lib/request.js:492:14)
    at Request._reply (/home/stefan/tmp/promster-issue/node_modules/@hapi/hapi/lib/request.js:446:18)
    at Request._execute (/home/stefan/tmp/promster-issue/node_modules/@hapi/hapi/lib/request.js:282:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This can be a problem for integration with other libraries (e.g. NextJS or Apollo) as those might use the raw response to write their responses.

**To Reproduce**
Steps to reproduce the behavior: Run the minimal example code from below.

1. Given I request `/does-not-work`
2. Then an unhandled rejection is thrown
3. That might crash the application (depending how unhandled promise rejections are handled)

**Expected behavior**
Promster does not include the response in the response size metric, or reads the header from the raw response.

**Additional context**

Minimal example:
```js
const { createPlugin } = require('@promster/hapi');
const Hapi = require('@hapi/hapi');

process.on('unhandledRejection', (err) => {
    console.log(err);
    process.exit(1);
});

(async () => {
    const server = Hapi.server({
        port: 3000,
        host: 'localhost'
    });
    
    await server.register(createPlugin());

    // Default way to render route response works fine
    server.route({
        method: 'GET',
        path: '/works',
        handler: (request, h) => {
            return 'Hello World!';
        }
    });

    // Using raw reponse causes unhandled promise rejection
    server.route({
        method: 'GET',
        path: '/does-not-work',
        handler: (request, h) => {
            request.raw.res.statusCode = 200;
            request.raw.res.write("Hello World!");
            return h.close;
        }
    });
    
    await server.start();
})();
```

**Comment by tdeekens** [comment]
Thanks for the issue and sorry for the trouble. I will try a fix to access the headers optionally. I found the documentation on accessing headers with Hapi quite confusing to be honest.

**Comment by tdeekens** [comment]
I am releasing `@promster/hapi@6.1.1` which should fix the issue. If it does please close the issue. Thanks.

**Comment by selaux** [comment]
Hi. Thanks for the quick response and fix. The issue doesn't manifest itself anymore for me with the new version. I had a quick look at the fix and have one question about it:  Won't the fix lead to empty requests & responses not being included in metrics anymore, because of e.g. `request?.headers?.['content-length']` evaluating to 0?

**Comment by tdeekens** [comment]
That's a good point. You'd suggest that an empty request or response would default to 0, right? Would you mind spinning up a PR for it? Extra ✋🏼 for a test case :)

**Comment by tdeekens** [comment]
Released in a new version to default to 0.
