### ISSUE TITLE
Add native support for GraphQL servers

### ISSUE THREAD

**Issue by 3commascapital** [tdeekens/promster#756]
**Is your feature request related to a problem? Please describe.**
any thoughts on supporting a graphql framework running on express or other servers?

**Describe the solution you'd like**
bring in the best prometheus implementations for graphql setups to present data in a comparable way or build out similar implementations

**Comment by tdeekens** [comment]
I've spend another hour or two to get the first demo and plugin setup off the ground. We can now record general GC metrics as usual but also additionally record request times and parsing times.

<img width="724" alt="CleanShot 2021-11-02 at 10 37 38@2x" src="https://user-images.githubusercontent.com/1877073/139826584-92f82ecc-fdb1-4d47-9c92-8fa8b7d9c2ed.png">
<img width="813" alt="CleanShot 2021-11-02 at 11 03 41@2x" src="https://user-images.githubusercontent.com/1877073/139826601-a7fb7c1f-a713-400b-ab37-1596d5a2f82c.png">
<img width="880" alt="CleanShot 2021-11-02 at 11 03 50@2x" src="https://user-images.githubusercontent.com/1877073/139826607-024f305b-8d19-4f56-be0b-2feedf4da88e.png">

Is this what you would expect initially from an Apollo Server plugin?

**Comment by tdeekens** [comment]
Update. It now looks like this.

<img width="957" alt="CleanShot 2021-11-03 at 13 03 21@2x" src="https://user-images.githubusercontent.com/1877073/140056749-32dfda3c-b6bc-4b7a-8800-dd4ee692e980.png">

**Comment by tdeekens** [comment]
Next iteration

![Uploading CleanShot 2021-11-03 at 22.07.29@2x.png…]()

**Comment by tdeekens** [comment]
@3commascapital I published an early version. Please have a look.
