### ISSUE TITLE
@promster/hapi has warning about unmet peer dependency

### ISSUE THREAD

**Issue by busches** [tdeekens/promster#761]
**Describe the bug**
When using `@promster/hapi`, which depends on `@promster/metrics` the following warning is outputted via `yarn`.

`warning "@promster/hapi > @promster/metrics > ts-essentials@9.0.0" has unmet peer dependency "typescript@>=4.1.0".`

**To Reproduce**

1. Given I have a package.json depending on `@promster/hapi`, e.g.:
```json
{
  "name": "example",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@promster/hapi": "^6.1.3"
  }
}
```
2. Then I run `yarn`
3. That gives the following warnings:
```
yarn add v1.22.17
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning @promster/hapi > @promster/metrics > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@promster/hapi > @promster/metrics@7.0.4" has unmet peer dependency "prom-client@13.x.x || 14.x".
warning "@promster/hapi > @promster/metrics > ts-essentials@9.0.0" has unmet peer dependency "typescript@>=4.1.0".
```

**Expected behavior**
Peer dependencies would be met by `@promster/hapi` or redeclared as a needed peer dependency of the package, so it's obvious that consumers of the package need to add the dependency themselves.

**Comment by tdeekens** [comment]
Thanks for the superb issue. I will fix the issue by adding a devDependency to the packages using ts-essentials.
