### ISSUE TITLE
`process.hrtime([time])` is no longer recommended for use

### ISSUE THREAD

**Issue by dogayuksel** [tdeekens/promster#790]
[Node.js documentation](https://nodejs.org/api/process.html#processhrtimetime) lists `process.hrtime([time])` as a [legacy feature](https://nodejs.org/api/documentation.html#stability-index). It is no longer recommended for use, and should be avoided.

Documentation recommends the use of `process.hrtime.bigint()`, that works slightly different. It does not support an additional time argument since bigint that it returns can easily be subtracted to find the difference.

Example from the [documentation](https://nodejs.org/api/process.html#processhrtimebigint):
```
import { hrtime } from 'process';

const start = hrtime.bigint();
// 191051479007711n

setTimeout(() => {
  const end = hrtime.bigint();
  // 191052633396993n

  console.log(`Benchmark took ${end - start} nanoseconds`);
  // Benchmark took 1154389282 nanoseconds
}, 1000);
```

**Comment by tdeekens** [comment]
Thanks @dogayuksel for reporting. Honestly, totally wasn't aware! :) Will assign you to a PR once ready if you don't mind.
