### ISSUE TITLE
TYPE up gauge always returns 0

### ISSUE THREAD

**Issue by mpx2m** [tdeekens/promster#829]
**Describe the bug**
Does TYPE up gauge always return 0 whether server is started or not?

**To Reproduce**

1. clone the repo
2. cd to demo
3. npm install : express、@promster/express、@promster/server
4. node ./express.js

**Expected behavior**

```
❯ node ./express.js
Prometheus metrics available on http://localhost:8080
Express app listening at http://localhost:80
```

http://localhost/  ----> I am the server!
http://localhost:8080/ -----> as Screenshots, TYPE up gauge returns 0

**Screenshots**
![image](https://user-images.githubusercontent.com/27198508/147212287-0c903873-5b67-43bf-90da-9dbe357ab693.png)

**Additional context**

**Comment by tdeekens** [comment]
Thanks for reporting this issue. However, it is actually not a bug but intended. `promster` can't know when your server is ready. Assuming so when your middleware has been called would work in some but certainly not all cases. Your server might depend on external resources such as a database connection or upstream APIs. In such cases it might be worthwhile to not report your sever as up right away as those dependencies resolve asynchronously. 

As a result to this you have to decide when your server is ready and when not by

```js
const { signalIsUp, signalIsNotUp } = require('@promster/express');

// Somewhere when your server has booted
signalIsUp();

// Somewhere when your server shuts down
signalIsNotUp();
```

This is similar to what [lightship](https://github.com/gajus/lightship) does. I agree that the example should contain that so let me add that.

**Comment by ventr1x** [comment]
Am I missing something about this overall?
The exact opposite is an issue. As I see it looking through the source code it is just setting the value to 0 on signalIsNotUp and NOT pushing it as it should. Prometheus is obviously unable to ever figure out through this value if a server is down. What is the point of it?
