### ISSUE TITLE
Use NodeJS url module instead of deprecated transitive dependency

### ISSUE THREAD

**Issue by dhs3000** [tdeekens/promster#845]
**Describe the bug**
I get the following warning when using promster:
```
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```
This is due to `promster/metrics` using the (external) `url` package. NodeJS provides the same functionality which was deprecated for some time, [but that has been revoked](https://nodejs.org/api/url.html#legacy-url-api).

**To Reproduce**

1. Add promster to a project, for example `"@promster/express"`
2. Run `npm. install`
3. See the printed warning
```
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

**Expected behavior**
No deprecation warnings when using promster.

**Additional context**
* I tried to create a pull request and remove the dependency, but cannot get `commitizen` / the pre-commit hook to work
* The tests still run when just removing the dependency from [metrics/package.json](https://github.com/tdeekens/promster/blob/main/packages/metrics/package.json#L45)
* I used Node 16 (LTS)

**Comment by tdeekens** [comment]
Thanks for opening an issue. You could try to commit with `--no-verify` to skip commit checks if they're bothering you.

**Comment by tdeekens** [comment]
@dhs3000 the fix has been released. Enjoy. Thanks for your contribution.
