### ISSUE TITLE
TPromsterOptions incorrect property

### ISSUE THREAD

**Issue by gimerstedt** [tdeekens/promster#888]
**Describe the bug**
I did not deep-dive here but it looks like the property "buckets" on TPromsterOptions in the typings package might have the incorrect type. Should it not be `number[]` or `Array<number>` as opposed to `[number]`?

https://github.com/tdeekens/promster/blob/main/packages/types/src/index.ts#L20

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4Chm+XALmQG0QBXAWwCNoBdHPKo866Y+vZBI1KKOAJ4AeFjSgA+LAF8sWBAHsQAZzD4eyALyYGuQiQCMAGgBMhgMy1DO5EwMnzl69zumL0oA

**To Reproduce**

1. Given '...'
2. Then '....'
3. That '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tdeekens** [comment]
Thanks for opening an issue. 

I think you're absolutely correct. those properties should be an number[] and not a list of one element with a number. 

Would you mind opening a PR with a fix? You can add a changeset on the PR and we could get a fix out soon.

**Comment by tdeekens** [comment]
Will be released in next version.
